<script>
  import { shapeArray } from "./G1_MA_shapes"
  import { randomCorrect } from "../taskjs/right";
  import { randomWrong } from "../taskjs/wrong";

  let ques_Img = "";
  let rn_for_US = [];
  let user_resp = "";
  let showNext = "none";   
  let showPopUp;
  let c_Ans = "";
  let selectionArray = [
    {s_opt:""},
    {s_opt:""},
    {s_opt:""},
    
  ];
  let sArray = shapeArray;

  function initImgs() {
    c_Ans = null;
    //question image is generated by generating a random value and assigning a correct value to check the result
    let ques_rIn = Math.floor(Math.random() * sArray.length);
    ques_Img = sArray[ques_rIn].img_src;
    c_Ans = sArray[ques_rIn].s_name;
    console.log('inside init',{ques_Img})
    console.log('inside init',{c_Ans})
    //generation of user choices
    for(let i=0;i<selectionArray.length;i++){
      if(rn_for_US[i+2] == rn_for_US[i]){
        rn_for_US[i] = Math.floor(Math.random() * sArray.length);
        selectionArray[i].s_opt = sArray[rn_for_US[i]].s_name;
        console.log('generated options are',rn_for_US[i])
        //console.log('generated options are',selectionArray[i].s_opt)
      }
      else if(rn_for_US[i] == rn_for_US[i+1]){
        rn_for_US[i] = Math.floor(Math.random() * sArray.length);
        selectionArray[i].s_opt = sArray[rn_for_US[i]].s_name;
        console.log('generated options are',selectionArray[i].s_opt)
      }
    }
    //checking if the correct choice is present in the user selection
    let crt_choice_present = 0;
    for(let i=0;i<selectionArray.length;i++){
      if(selectionArray[i].s_opt == c_Ans){
        crt_choice_present++;
      }
    }
    //if the correct choice is not present in the user choices then it is displayed
    if(crt_choice_present == 0){
      console.log("crt opt not displayed")
      let rn1 = Math.floor(Math.random() * selectionArray.length);
      selectionArray[rn1].s_opt = c_Ans;
    }
    //incase of recurrance in user choices
    for(let i=0;i<selectionArray.length;i++){
      if(rn_for_US[i] == rn_for_US[i+1]){
        rn_for_US[i+1] = Math.floor(Math.random() * sArray.length);
      }
    }
      
    
    
    showPopUp = null;
    showNext = "none";
    //console.log("hi");
  }
  initImgs();
  
  function assign_resp(p_Ans) {
    user_resp = p_Ans;
  }

  function checkAns() {
    console.log('inside result')
    console.log('inside result',{user_resp})
    console.log('inside result',{c_Ans})
    showNext = "inline-block";
    if (user_resp == c_Ans) {
      showPopUp = randomCorrect();
      return;
    } else {
      showPopUp = randomWrong();
    }
  }
</script>

<!--markup starts here-->

<div>
  <h4>Two-Dimensional Shapes</h4>
  <h5>Name the two-dimensional shape</h5>
  <div class='myck'>
    <label for='myck'>
      <img src={ques_Img} alt="" width="30%" />
    </label>
  </div>
  <div>
    
      {#each selectionArray as item,i}
          <input type="button" on:click={() => assign_resp(item.s_opt)} value={item.s_opt}/>&nbsp;&nbsp;&nbsp;
      {/each}
   
    
  </div>
  <br>
  <h5 style=" display: {showNext};" class="mt-5">{showPopUp}</h5>
  
  <div>
    <button type="button" class="btn rerun" on:click={() => checkAns()}
      >Submit</button
    >
    <button type="button" class="btn rerun" on:click={() => initImgs()}
      >Rerun</button
    >
  </div>
  <p>the correct answer is {c_Ans}</p>
</div>

<style>
  img {
    
    width: 190px;
    transition-duration: 0.2s;
    transform-origin: 50% 50%;
  }
</style>
