<script>
  import { randomCorrect } from "../taskjs/right";
  import { randomWrong } from "../taskjs/wrong";

  let ques_Img = "";
  let rn_for_US = [];
  let user_resp = "";
  let showNext = "none";   
  let showPopUp;
  let c_Ans = "";
  let selectionArray = [
    {s_name:"",s_status:false},
    {s_name:"",s_status:false},
    {s_name:"",s_status:false},
    {s_name:"",s_status:false}
  ]
  let sArray = [
    { shape: "Circle", img_src: "images/shapes/blackCircle.png" },
    { shape: "Square", img_src: "images/shapes/blackSquare.png" },
    { shape: "Rectangle", img_src: "images/shapes/blackRectangle.png" },
    { shape: "Triangle", img_src: "images/shapes/blackTriangle.png" },
    { shape: "Hexagon", img_src: "images/shapes/blackHexagon.png" },
    { shape: "Octagon", img_src: "images/shapes/blackOctagon.png" },
    { shape: "Pentagon", img_src: "images/shapes/blackPentagon.png" },
  ];

  function initImgs() {
    c_Ans = null;
    user_resp = null;
    //question image is generated by generating a random value and assigning a correct value to check the result
    
    let ques_rIn = Math.floor(Math.random() * sArray.length);
    ques_Img = sArray[ques_rIn].img_src;
    c_Ans = sArray[ques_rIn].shape;
    //generation of user choices
    for(let i=0;i<selectionArray.length;i++){
      rn_for_US[i] = Math.floor(Math.random() * sArray.length);
      selectionArray[i].s_name = sArray[rn_for_US].shape
    }
    //checking if the correct choice is present in the user selection
    
    let crt_choice_present = 0;
    for(let i=0;i<selectionArray.length;i++){
      if(selectionArray[i].s_name == c_Ans){
        crt_choice_present++
      }
    }
    //if the correct choice is not displayed in the user choices
    if(crt_choice_present == 0){
      let rn1 = Math.floor(Math.random() * selectionArray.length)
      selectionArray[i].s_name = c_Ans;
    }
    
    showPopUp = null;
    showNext = "none";
    //console.log("hi");
  }
  initImgs();

  function assign_resp(p_Ans) {
    user_resp = p_Ans;
  }

  function checkAns() {
    //user_resp = p_Ans ;
    console.log("ans check: ", user_resp);
    showNext = "inline-block";
    if (user_resp == c_Ans) {
      //def_ans = true;
      showPopUp = randomCorrect();
      return;
    } else {
      //def_ans = true;
      showPopUp = randomWrong();
    }
  }
</script>

<div>
  <h4>Two-Dimensional Shapes</h4>
  <h5>Name the two-dimensional shape</h5>
  <div class='myck'>
    <label for='myck'>
      <img src={ques_Img} alt="" width="30%" />
    </label>
  </div>
  <div>
    {#each selectionArray as item,i}
      <li>
        <input type="checkbox" id={"check" + i} bind:checked={item.s_Status}/>
        <label for={"check" + i}>
          <p>{item}</p>
        </label>
      </li>
    {/each}
    
    
  </div>
  <br>
  <h5 style=" display: {showNext};" class="mt-5">{showPopUp}</h5>
  
  <div>
    <button type="button" class="btn rerun" on:click={() => checkAns()}
      >Submit</button
    >
    <button type="button" class="btn rerun" on:click={() => initImgs()}
      >Rerun</button
    >
  </div>
  <p>the correct answer is {c_Ans}</p>
</div>

<style>
  img {
    height: 100px;
    width: 100px;
    transition-duration: 0.2s;
    transform-origin: 50% 50%;
  }
</style>
